# Generated by Django 6.1 on 2026-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.CharField(max_length=150)),
                ('source_ip', models.GenericIPAddressField()),
                ('action', models.CharField(max_length=100)),
                ('asset', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('incident_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
