# Generated by Django 6.0.1 on 2026-08-07 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attacker'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityevent',
            name='attacker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='core.attacker'),
        ),
    ]
